<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Main.aspx.cs" Inherits="Main" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
	<title></title>
</head>
<body>
	<form id="form1" runat="server">
		<div>
			<asp:SqlDataSource ID="ds1" runat="server" SelectCommand="select *  from [staff]" ConnectionString="<%$ConnectionStrings:db%>"
				UpdateCommand="update [staff] set [name]=@name, [age]=@age, [destination]=@destination, [salary]=@salary where name=@name"
				InsertCommand="insert into [staff] values (@name, @age, @destination, @salary)"
				DeleteCommand="delete from [staff] where name=@name"
				/>
			<asp:GridView ID="gv1" DataKeyNames="name" DataSourceID="ds1" AutoGenerateSelectButton="true" AutoGenerateDeleteButton="true" AutoGenerateColumns="false" AllowSorting="true" runat="server" AllowPaging="true" PageSize="4" OnRowDataBound="gv1_RowDataBound">
				<Columns>
					<asp:TemplateField SortExpression="age">
						<HeaderTemplate>
							<asp:LinkButton ID="lb" runat="server" Text="Staff Details" CommandName="sort" CommandArgument="age"/>
						</HeaderTemplate>
						<ItemTemplate>
							<b>Name </b><%#Eval("name") %>
							<br />
							<b>Age</b> <%#Eval("age") %>
						</ItemTemplate>
						<EditItemTemplate>
							<asp:RangeValidator ID="age_val" runat="server" ControlToValidate="age_change" MaximumValue="50" MinimumValue="20" ErrorMessage="Age not in range"/>
							<b>Name </b>
							<asp:TextBox ID="name_change" Text='<%#Bind("name") %>' runat="server" />
							<br />
							<b>Age</b> 
							<asp:TextBox ID="age_change" Text='<%#Bind("age") %>' runat="server" />
						</EditItemTemplate>
						<InsertItemTemplate>
							<b>Name </b>
							<asp:TextBox ID="name_new" Text='<%#Bind("name") %>' runat="server" />
							<br />
							<b>Age</b> 
							<asp:TextBox ID="age_new" Text='<%#Bind("age") %>' runat="server" />
						</InsertItemTemplate>
					</asp:TemplateField>
					<asp:BoundField DataField="destination" HeaderText="Destination" SortExpression="destination"/>
					<asp:BoundField DataField="salary" HeaderText="Salary" SortExpression="salary"/>
					<asp:CommandField ShowEditButton="true" CausesValidation="true" />
				</Columns>
			</asp:GridView>
		</div>
	</form>
</body>
</html>
